import{useMemo,useState}from'react';import{Activity,BookOpen,Clock3,FlaskConical,HeartPulse,History,MessageCircle,Stethoscope}from'lucide-react';import{cases}from'./data';import{advance,availableExam,createSession,scoreCase}from'./engine';import{storage}from'./storage';import{CaseTemplate,Mode,Session}from'./types';
type View='dashboard'|'new'|'room'|'library'|'history'|'debrief';
const fmt=(m:number)=>`${Math.floor(m/60)}h ${m%60}min`;
export default function App(){const[start]=useState(()=>storage.load());const[session,setSession]=useState<Session|null>(start);const[view,setView]=useState<View>(start?'room':'dashboard');const[tab,setTab]=useState('Conversa');const current=useMemo(()=>cases.find(c=>c.id===session?.caseId)||null,[session]);const update=(s:Session)=>{setSession(s);storage.save(s)};
function begin(c:CaseTemplate,mode:Mode){const s=createSession(c,mode);update(s);setView('room')}
function finish(){if(!session||!current)return;const s={...session,finished:true,outcome:'Caso encerrado para debriefing'};update(s);storage.push({caseId:current.id,diagnosis:current.diagnosis,date:new Date().toISOString(),outcome:s.outcome!,score:scoreCase(s,current)});setView('debrief')}
return <div className="app"><header><div className="brand"><HeartPulse size={28}/><div><b>MedSim</b><span>Paciente virtual educacional</span></div></div><nav>{[['dashboard','Início'],['new','Novo caso'],['library','Biblioteca'],['history','Histórico']].map(([v,l])=><button key={v} onClick={()=>setView(v as View)}>{l}</button>)}</nav></header><div className="notice">Uso exclusivamente educacional — não destinado a diagnóstico ou tratamento de pacientes reais.</div><main>
{view==='dashboard'&&<section><div className="hero"><div><span className="eyebrow">TREINO CLÍNICO INTERATIVO</span><h1>Aprenda acompanhando a evolução de pacientes virtuais.</h1><p>Entreviste, examine, solicite exames, registre hipóteses, escolha condutas e avance o relógio clínico.</p><button className="primary" onClick={()=>setView('new')}>Iniciar novo caso</button></div><Activity size={110}/></div><div className="grid three"><Card icon={<MessageCircle/>} title="Anamnese ativa" text="Perguntas mudam o que você sabe, não o relógio clínico."/><Card icon={<Clock3/>} title="Evolução temporal" text="Avance 30 min, 2 h, 6 h ou 1 dia e observe o quadro."/><Card icon={<Stethoscope/>} title="Debriefing" text="Compare pistas, exames, condutas e seu raciocínio."/></div></section>}
{view==='new'&&<section><h1>Novo caso</h1><p className="muted">Escolha um modo e uma situação clínica.</p><div className="mode-row">{(['study','surprise','directed'] as Mode[]).map(m=><span className="chip" key={m}>{m==='study'?'Estudar patologia':m==='surprise'?'Caso surpresa':'Treino direcionado'}</span>)}</div><div className="grid">{cases.map(c=><article className="case-card" key={c.id}><span>{c.specialty}</span><h3>{c.diagnosis}</h3><p>{c.presentation}</p><small>{c.difficulty}</small><div className="actions"><button onClick={()=>begin(c,'study')}>Estudar</button><button className="primary" onClick={()=>begin(c,'surprise')}>Surpresa</button></div></article>)}</div></section>}
{view==='room'&&session&&current&&<Room s={session} c={current} tab={tab} setTab={setTab} update={update} finish={finish}/>}
{view==='library'&&<section><h1>Biblioteca de patologias</h1><div className="grid">{cases.map(c=><article className="case-card" key={c.id}><BookOpen/><h3>{c.diagnosis}</h3><p>{c.specialty} · {c.difficulty}</p><ul>{c.clues.map(x=><li key={x}>{x}</li>)}</ul><button onClick={()=>begin(c,'study')}>Abrir caso</button></article>)}</div></section>}
{view==='history'&&<section><h1>Histórico</h1>{storage.history().length===0?<p className="empty">Nenhum caso finalizado ainda.</p>:storage.history().map((h,i)=><div className="history" key={i}><div><b>{h.diagnosis}</b><span>{new Date(h.date).toLocaleString('pt-BR')}</span></div><strong>{h.score}/100</strong></div>)}</section>}
{view==='debrief'&&session&&current&&<section><span className="eyebrow">DEBRIEFING</span><h1>{current.diagnosis}</h1><div className="score">{scoreCase(session,current)}<span>/100</span></div><div className="grid two"><article className="panel"><h3>Pistas principais</h3><ul>{current.clues.map(x=><li key={x}>{x}</li>)}</ul></article><article className="panel"><h3>Seu percurso</h3><p>Perguntas feitas: {session.asked.length}</p><p>Exames solicitados: {session.ordered.length}</p><p>Condutas aplicadas: {session.applied.length}</p><p>Tempo clínico: {fmt(session.time)}</p></article></div><article className="panel"><h3>Referências e segurança</h3>{current.references.map(x=><p key={x}>{x}</p>)}</article><button className="primary" onClick={()=>setView('new')}>Treinar outro caso</button></section>}
</main></div>}
function Card(p:{icon:any,title:string,text:string}){return <article className="panel">{p.icon}<h3>{p.title}</h3><p>{p.text}</p></article>}
function Room({s,c,tab,setTab,update,finish}:{s:Session,c:CaseTemplate,tab:string,setTab:(x:string)=>void,update:(x:Session)=>void,finish:()=>void}){const tabs=['Conversa','Exame físico','Exames','Hipóteses','Conduta'];const diagnosis=s.mode==='surprise'?'Diagnóstico oculto':c.diagnosis;return <section><div className="patient-head"><div><span className="eyebrow">{diagnosis}</span><h1>{c.patient.name}, {c.patient.age} anos</h1><p>{c.presentation}</p></div><div className="timebox"><Clock3/> {fmt(s.time)}</div></div><div className="vitals"><V label="FC" v={s.vitals.hr+' bpm'}/><V label="PA" v={s.vitals.bp}/><V label="FR" v={s.vitals.rr+' irpm'}/><V label="SpO₂" v={s.vitals.spo2+'%'}/><V label="Temp" v={s.vitals.temp+' °C'}/></div><div className="tabs">{tabs.map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><div className="workspace">
<div className="panel room-panel">
{tab==='Conversa'&&<div><h3>Entrevista</h3>{c.questions.map(x=><div className="qa" key={x.q}><button disabled={s.asked.includes(x.q)} onClick={()=>update({...s,asked:[...s.asked,x.q]})}>{x.q}</button>{s.asked.includes(x.q)&&<p>“{x.a}”</p>}</div>)}</div>}
{tab==='Exame físico'&&<div><h3>Exame físico</h3><ul>{c.physical.map(x=><li key={x}>{x}</li>)}</ul></div>}
{tab==='Exames'&&<div><h3>Exames</h3>{c.exams.map(e=><div className="order" key={e.name}><div><b>{e.name}</b><small>resultado em ~{e.availableAt} min</small></div>{!s.ordered.includes(e.name)?<button onClick={()=>update({...s,ordered:[...s.ordered,e.name],timeline:[...s.timeline,{time:s.time,text:'Solicitado: '+e.name,severity:'stable'}]})}>Solicitar</button>:availableExam(s,c,e.name)?<strong>{e.value}</strong>:<span>Aguardando</span>}</div>)}</div>}
{tab==='Hipóteses'&&<Hyp s={s} update={update}/>}
{tab==='Conduta'&&<div><h3>Condutas</h3>{c.treatments.map(t=><label className="treatment" key={t.id}><input type="checkbox" checked={s.applied.includes(t.id)} onChange={e=>update({...s,applied:e.target.checked?[...s.applied,t.id]:s.applied.filter(x=>x!==t.id),timeline:[...s.timeline,{time:s.time,text:(e.target.checked?'Iniciado: ':'Suspenso: ')+t.label,severity:'stable'}]})}/><span>{t.label}</span></label>)}</div>}
</div><aside><div className="panel"><h3>Avançar tempo</h3><div className="advance">{[30,120,360,1440].map(m=><button key={m} onClick={()=>update(advance(s,c,m))}>+{m===1440?'1 dia':m<60?m+' min':m/60+' h'}</button>)}</div></div><div className="panel"><h3>Linha do tempo</h3>{[...s.timeline].reverse().slice(0,7).map((e,i)=><div className={'event '+e.severity} key={i}><b>{fmt(e.time)}</b><span>{e.text}</span></div>)}</div><button className="primary full" onClick={finish}>Encerrar e revisar</button></aside></div></section>}
function Hyp({s,update}:{s:Session,update:(x:Session)=>void}){const[val,setVal]=useState('');return <div><h3>Hipóteses diagnósticas</h3><div className="inline"><input value={val} onChange={e=>setVal(e.target.value)} placeholder="Digite uma hipótese"/><button onClick={()=>{if(val.trim()){update({...s,hypotheses:[...s.hypotheses,val.trim()]});setVal('')}}}>Adicionar</button></div><ol>{s.hypotheses.map(x=><li key={x}>{x}</li>)}</ol></div>}
function V({label,v}:{label:string,v:string}){return <div><span>{label}</span><b>{v}</b></div>}
